### ISSUE TITLE
Class names should be capital

### ISSUE THREAD

**Issue by khalil2535** [itsDARKSAMA/java-ds#1]
[LinkedList](https://github.com/itsDARKSAMA/java-ds/blob/086d34127022923c0c75ebec082fff7c33ad873c/singly_linkedlist/linkedList.java#L3) class should start with a Capital letter instead of the small one.

https://github.com/itsDARKSAMA/java-ds/blob/086d34127022923c0c75ebec082fff7c33ad873c/singly_linkedlist/linkedList.java#L3

So for [Main](https://github.com/itsDARKSAMA/java-ds/blob/086d34127022923c0c75ebec082fff7c33ad873c/singly_linkedlist/main.java#L3) class

https://github.com/itsDARKSAMA/java-ds/blob/086d34127022923c0c75ebec082fff7c33ad873c/singly_linkedlist/main.java#L3

**Comment by itsDARKSAMA** [comment]
Thanks
